language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  keep-history: true
  on:
    branch: master